dist: xenial # required for python >= 3.7
language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: torchkge
  password:
    secure: GJPIeZGmkDII0/wZLPrI0OfRlKkkZ7zTHqxcP0Jx91VIV1DBNXziQNi/ihAx2J978K05r1aqbuPm+Wo0T+zlG2XbklOu7oHqRNqObDaVaE2LPprKbhYEnisvW9F/dy5p/gOrOF8fg0yvIxOvVfkDLdGHw8DNy5usvOCZTaj6F4CTGtNH9uTdSPjvEq6vLevLX0S64oxY535QZEToXZwIFtRW5tqfSEQ1ykTSdcSNuGHisbnGlGzajG+afzhG83RE5JvhBEkUH3nApNLdKgWai3Q155BNZhhHylKlYMnYrKpZz2UAP5kXBM+GbtjAlPRCmcbaiwxCglUOyItS8+6fbsOC7PqhEAi4MbUOXL0hPE1JqPrsQbTLO1WHNHb68z1E+FLKEMWjjkMbNNmonyBNzQI8Gg1t00En4MNiGUckX22HzRrHViiFHmqtxsqRdhJHL/Cue2eAbI5hwmB923HeeK89TIjfrBVFKK/YyrjoyrPJZai4DzI6eNcguXiCa03zLAazM+LNX2MKZbzDomAWT1Pxviq4TezcNYlEoJ2LSvleTrNaGBgPqXOoNDUQ3pjMa2pm4oJw8jpm9AH4SglG6ABnaaZdu+wQj2FX6IpYhwR5f5PFHuLi32gjLeMzHltpgTJ2ANyCNbTbY7sC3mWaRZEJ4jCwkmhJOdw9ySaTIiM=
  on:
    tags: true
    repo: torchkge/torchkge
    python: 3.6
