dist: xenial
language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: torchkge
  password:
    secure: eAcmd8UYJO+grYMwFALR9vgdlZnZY2zynO16slijnquj31NRznS+MRR3DiiAcVsOm+MXpMEELT68xGUzyCvyTKpg410lvZRsEdlDwpiELfFz4E0ZfuulL4QwiQfcD/7cWXzlmGVKBSQBH0lEN2+BY3PT/2iW0pk99yMVx/xQYWJZIQPVaX9AHUFWB+k66witsJdbKW4dRa/9vYTTi2nQhfwWOFT0Ap+dcM8ovM1t/b0fCAspg4+2LHeTejTG7zhv3ZHqSdBdtVDpXXeY/gDPzqSme7IierklPyuAwZEJaXK51QVgz8DXVbDdGlQBtfEExN0DUNOnveRatNZqVAsUwQ7hflrjALNg7V/xaQEE0pnoQSNc2rsvJT2kjaFNJVpCNmRjUNycfq0h0ADgX6se7+rkkNxZhNfre7yMPzpx+2FS/Tn2E2Zeqbx4qiHeWIyopONimu6nCwL8weJw5R375/9+zWSgHxwr0KD1wu2YCh1Rl5z5MMrSh2fDGr6axHRYL+/feEhXDqhWuOUIDNmXfc6BZa/SrBIDJDUh5VSZX1BqnOy9Aw/6VO4H7tsKRjsjhrBJYtWXdY6huPoTfSJdB2inKk5dzffJPJdDHWs7Na0f7y5MTOvdPL8mG9oWpDNilHHEWrljrrbv1FX0FyKSeF1z8pNp/u9svavxkzA8z1w=
  on:
    tags: true
    repo: torchkge/torchkge
    python: 3.6
